### ISSUE TITLE
01/01/2020 იდან ფორმები შეიცვალა

### ISSUE THREAD

**Issue by nikopeikrishvili** [notgiorgi/virtual-person-taxes#6]
პირველი იანვრიდან ფორმაბი შეიცვალა გაერთიანდა 2 ფორმა და ეხლა 3 ის მაგივრად ბარდება 2 ფორმა

**Comment by notgiorgi** [comment]
გამარჯობა @nikopeikrishvili 

საშემოსავლოს ფორმა რომ შეიცვალა ეგ დავააფდეითე: #8

რომელი აღარ ბარდება შეგიძლია მითხრა? შევცვლი მაგასაც. ბოლო ორი თვეა მაინც სამივეს ვაბარებდი მე 😅

**Comment by nikopeikrishvili** [comment]
ინფორმაცია ფ/პ-ებზე დაკავებული საშ.გად. შესახებ (**განაცემთა**)
ეს აღარ ივსება გაერთიანდა საშემოსავლო გადასახადთან რამდენადაც ვიცი
